CREATE TABLE CUSTOMERS (
  CUSTOMER_ID NUMBER(10),
  CUSTOMER_NAME VARCHAR(100),
  EMAIL VARCHAR(100),
  PHONE VARCHAR(20),
  ADDRESS VARCHAR,
  CREDIT_LIMIT NUMBER(12,2),
  CUSTOMER_TYPE VARCHAR(20),
  CREATED_DATE TIMESTAMP_NTZ
);

CREATE TABLE CUSTOMERS (
    CUSTOMER_ID     NUMBER(10,0)   NOT NULL,
    CUSTOMER_NAME   VARCHAR(100)   NOT NULL,
    EMAIL           VARCHAR(100),
    PHONE           VARCHAR(20),
    ADDRESS         VARCHAR(10000),
    CREDIT_LIMIT    NUMBER(12,2),
    CUSTOMER_TYPE   VARCHAR(20),
    CREATED_DATE    TIMESTAMP_NTZ  DEFAULT CURRENT_TIMESTAMP(),

    CONSTRAINT PK_CUSTOMERS PRIMARY KEY (CUSTOMER_ID),
    CONSTRAINT UQ_CUSTOMERS_EMAIL UNIQUE (EMAIL)
);
