CREATE TABLE ORDERS (
  ORDER_ID NUMBER(10),
  CUSTOMER_ID NUMBER(10),
  ORDER_DATE TIMESTAMP_NTZ,
  TOTAL_AMOUNT NUMBER(12,2),
  DISCOUNT_AMOUNT NUMBER(10,2),
  TAX_AMOUNT NUMBER(10,2),
  STATUS VARCHAR(20),
  CREATED_AT VARCHAR
);

CREATE TABLE ORDERS (
    ORDER_ID        NUMBER(10,0)   NOT NULL,
    CUSTOMER_ID     NUMBER(10,0)   NOT NULL,
    ORDER_DATE      TIMESTAMP_NTZ  NOT NULL,
    TOTAL_AMOUNT    NUMBER(12,2),
    DISCOUNT_AMOUNT NUMBER(10,2),
    TAX_AMOUNT      NUMBER(10,2),
    STATUS          VARCHAR(20),
    CREATED_AT      TIMESTAMP_NTZ  DEFAULT CURRENT_TIMESTAMP(),

    CONSTRAINT PK_ORDERS PRIMARY KEY (ORDER_ID),
    CONSTRAINT FK_ORDERS_CUSTOMER
        FOREIGN KEY (CUSTOMER_ID)
        REFERENCES CUSTOMERS (CUSTOMER_ID)
)
CLUSTER BY (ORDER_DATE);
