CREATE TABLE ORDER_ITEMS (
  ORDER_ITEM_ID NUMBER(10),
  ORDER_ID NUMBER(10),
  PRODUCT_ID NUMBER(10),
  QUANTITY NUMBER(10),
  UNIT_PRICE NUMBER(10,2)
);

CREATE TABLE ORDER_ITEMS (
    ORDER_ITEM_ID   NUMBER(10,0)   NOT NULL,
    ORDER_ID        NUMBER(10,0)   NOT NULL,
    PRODUCT_ID      NUMBER(10,0)   NOT NULL,
    QUANTITY        NUMBER(10,0)   NOT NULL,
    UNIT_PRICE      NUMBER(10,2)   NOT NULL,

    CONSTRAINT PK_ORDER_ITEMS PRIMARY KEY (ORDER_ITEM_ID),
    CONSTRAINT FK_OI_ORDER
        FOREIGN KEY (ORDER_ID)
        REFERENCES ORDERS (ORDER_ID),
    CONSTRAINT FK_OI_PRODUCT
        FOREIGN KEY (PRODUCT_ID)
        REFERENCES PRODUCTS (PRODUCT_ID)
);
