CREATE TABLE PRODUCTS (
  PRODUCT_ID NUMBER(10),
  PRODUCT_NAME VARCHAR(200),
  CATEGORY_ID NUMBER(10),
  UNIT_PRICE NUMBER(10,2),
  STATUS VARCHAR(20),
  CREATED_DATE TIMESTAMP_NTZ
);

CREATE TABLE PRODUCTS (
    PRODUCT_ID      NUMBER(10,0)   NOT NULL,
    PRODUCT_NAME    VARCHAR(200)   NOT NULL,
    CATEGORY_ID     NUMBER(10,0),
    UNIT_PRICE      NUMBER(10,2)   NOT NULL,
    STATUS          VARCHAR(20),
    CREATED_DATE    TIMESTAMP_NTZ  DEFAULT CURRENT_TIMESTAMP(),

    CONSTRAINT PK_PRODUCTS PRIMARY KEY (PRODUCT_ID),
    CONSTRAINT FK_PRODUCTS_CATEGORY
        FOREIGN KEY (CATEGORY_ID)
        REFERENCES CATEGORIES (CATEGORY_ID)
);
