CREATE TABLE CATEGORIES (
  CATEGORY_ID NUMBER(10),
  CATEGORY_NAME VARCHAR(100),
  DESCRIPTION VARCHAR(500)
);

CREATE TABLE CATEGORIES (
    CATEGORY_ID     NUMBER(10,0)   NOT NULL,
    CATEGORY_NAME   VARCHAR(100)   NOT NULL,
    DESCRIPTION     VARCHAR(500),

    CONSTRAINT PK_CATEGORIES PRIMARY KEY (CATEGORY_ID),
    CONSTRAINT UQ_CATEGORY_NAME UNIQUE (CATEGORY_NAME)
);
